---
title: "Download_Installation"
author: "AY"
date: "`r format(Sys.Date())`"
output:
  html_document:
    highlight: haddock
    number_sections: yes
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: no
      smooth_scroll: no
---

# Download
Downloading and using the software is free of charge. 

Simply download from [here](https://maxquant.org/) and unpack the compressed file //MaxQuant.zip//.

# Running 
Please choose your operating system to view how to run MaxQuant.

## MaxQuant on Windows

Supported operation system versions (64 bit is required) are Windows Vista, 7, 8, 10,11 or Server 2008, 2012, 2016, 2019

  * **Install .NET Framework 4.7.3 or higher**: To find out whether you already have it, follow the instructions on [How to Determine Which .NET Framework Versions Are Installed](http://msdn.microsoft.com/en-us/library/hh925568%28v=vs.110%29.aspx#net_b). If you need to, you can download the software and get installation instructions at the [Microsoft Download Center](http://www.microsoft.com/en-us/download/details.aspx?id=30653).
  
  We are currently working on making MaxQuant compatible with .Net 6. This will be bring further advantages to speed and stability of the tool. 

  * **Run MaxQuant GUI**
Double click on //MaxQuant.exe// in //MaxQuant// folder and specify your RAW files, experimental design and fasta files.

  *  **Start MaxQuant**
Click on the //Start// button.


## MaxQuant on Linux

We are supporting MaxQuant on Ubuntu 16 or higher, but MaxQuant should also work on another distribution of Linux. 
You may run MaxQuant using Graphical User Interface. In this case, you should install Mono and follow instructions for //MaxQuant on Windows// starting from second point. This tutorial is focused on running MaxQuant using command line.


  * **Install .NET Core 3.1** \\ 
To find out whether you already have it, type in the command line

```{bash, eval=FALSE}
dotnet --version
```

If you see at least the version //3.1.100//, then everything is ready to start MaxQuant.

Otherwise you need to get installation instructions at the [.NET Core SDK 3.1](https://dotnet.microsoft.com/en-us/download/dotnet/3.1) for your operation system.

Ubuntu 20.04 (for example)

```{bash, eval = FALSE}
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update; \
sudo apt-get install -y apt-transport-https && \
sudo apt-get update && \
sudo apt-get install -y dotnet-sdk-2.1
```

  * **Edit //mqpar.xml// file**
Currently we highly recommend to preconfigure the //mqpar.xml// file in MaxQuant GUI. After transferring the file on Linux machine, do not forget to update file addresses accordingly. You can also use a programmatic way to change that.

```{bash, eval=FALSE}
dotnet MaxQuant/bin/MaxQuantCmd.exe --changeFolder=new_mqpar.xml <new folder with fasta files> <new folder with raw files> old_mqpar.xml
```

However if you feel familiar with a structure of mqpar.xml, you may create a template of mqpar.xml and edit it directly.

```{bash, eval=FALSE}
dotnet MaxQuant/bin/MaxQuantCmd.exe --create new_mqpar.xml
```

  * **Run MaxQuant**
  
```{bash, eval=FALSE}
dotnet MaxQuant/bin/MaxQuantCmd.exe mqpar.xml
```

# Hardware requirements
  * 4 GB RAM minimum.
  * 4 GB RAM per thread that is executed in parallel is required.
  * There is no upper limit on the number of cores. Whatever you can fit into a shared memory machine will work as long as the disk performance scales up with it.